version: '3.8'

services:
  dmi_shield_app:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "${SHIELD_PORT}:4200"
   restart: unless-stopped
   env_file:
    - ./environment/.env.${ENVIRONMENT} 
