name: Deploy SH.I.E.L.D
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy S.H.I.E.L.D
    runs-on: ubuntu-latest
    steps:
    - name: updating and deploying S.H.I.E.L.D
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/lib/shield_prod/dmi-shield-frontend
          sudo git switch main
          sudo git pull
          sudo cp -rf /var/lib/shield_prod/config_files/* src/app/
          sudo docker compose up -d --build --force-recreate --no-deps
          sudo systemctl restart nginx
          echo "S.H.I.E.L.D is now LIVE!!"
